# -*- mode: ruby -*-
# vi: set ft=ruby :

# Main Vagrantfile that relies on the docker provider of Vagrant to
# start 2 docker containers. Should be portable on Linux and Windows

# Avoid the need to explicitely start with vagrant up --provider=docker
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Explicitely set to true to trigger boot2docker VirtualBox VM invocation on Linux too
#FORCE_HOST_VM = false
FORCE_HOST_VM = true

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # First the PostgreSQL docker container
  config.vm.define "postgre" do |postgre|
    postgre.vm.provider "docker" do |d|

      d.force_host_vm = FORCE_HOST_VM

      d.name = "tsp-moocdb-postgres"
      d.build_dir = "docker-buildenv/tsp-moocdb-postgres"
      d.build_args = ["-t=tsp-moocdb-postgres"]
      
      # Use a custom boot2docker VM instead of default one
      d.vagrant_vagrantfile = 'Vagrantfile_hostVM'
    end
  end

  # Then the Web app container
  config.vm.define "webapp" do |webapp|
    webapp.vm.provider "docker" do |d|

      d.force_host_vm = FORCE_HOST_VM

      d.name = "tsp-moocdb-web"
      d.build_dir = "docker-buildenv/tsp-moocdb-web"
      d.build_args = ["-t=tsp-moocdb-web"]

      # Relies on the postgres container
      d.link "tsp-moocdb-postgres:tsp-moocdb-postgres"
      d.vagrant_vagrantfile = 'Vagrantfile_hostVM'

      # The 8080 port will be forwarded to the 80 port
      d.ports = ["8080:80"]

    end
  end

  # Make the provisionning dirs available
  config.vm.synced_folder "docker-buildenv/tsp-moocdb-postgres", "/vagrant_data-postgres", type: "rsync"
  config.vm.synced_folder "docker-buildenv/tsp-moocdb-web", "/vagrant_data-web", type: "rsync"

end
