# -*- coding: utf-8; mode: ruby -*-
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

  # Debian Jessie base box : Debian Jessie amd64 (by default, or i686 for 32bits) minimal w/ guest additions

  config.vm.define "bits32", autostart: false do |bits32|
    bits32.vm.box = "oberger/debianjessiemini-i686"
    # workaround the incorrect ostype set by bootstrap-vz
    bits32.vm.provider "virtualbox" do |vb32|
      vb32.customize ["modifyvm", :id, "--ostype", "Debian"]
    end 
  end
  
  config.vm.define "bits64", primary: true do |bits64|
    bits64.vm.box = "oberger/debianjessiemini-amd64"
    bits64.vm.provider "virtualbox" do |vb64|
      vb64.customize ["modifyvm", :id, "--ostype", "Debian_64"]
    end
  end

  # Setup the containers when the VM is first
  # created
  config.vm.provision "shell", path:"./setup-debian/provisioning.sh"

  # config.vm.network "private_network", ip: "192.168.50.40"

  # Forward port to access the guest machine
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Uncomment the following to access the GUI
  # config.vm.provider "virtualbox" do |v|
  #   v.gui = true
  # end
end
