# -*- coding: utf-8; mode: ruby -*-
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

  # Box de base Debian : Debian Jessie amd64 minimal w/ guest additions

  config.vm.box = "oberger/debianjessiemini-amd64"


  # Setup the containers when the VM is first
  # created
  config.vm.provision "shell", path:"./setup-debian/provisioning.sh"

  # config.vm.network "private_network", ip: "192.168.50.40"

  # Forward port to access the guest machine
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Setting up synced folders so that students can use their own php pages

#   config.vm.synced_folder "./appli", "/var/www/html/"


#  config.vm.synced_folder "./setup-debian","/home/vagrant"

  # Make sure the correct processes are running
  # every time we start the VM.
  # config.vm.provision "shell", run: "always", path:""

  # Uncomment the following to access the GUI
  # config.vm.provider "virtualbox" do |v|
  #   v.gui = true
  # end
end
