# -*- coding: utf-8; mode: ruby -*-
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

  # Box de base Debian : Debian Jessie amd64 minimal w/ guest additions

  config.vm.box = "oberger/debianjessiemini-amd64"


  # Setup the containers when the VM is first
  # created
  config.vm.provision "shell", path:"./setup-debian/provisioning.sh"

  # config.vm.network "private_network", ip: "192.168.50.40"

  # Forward port to access the guest machine
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Uncomment the following to access the GUI
  # config.vm.provider "virtualbox" do |v|
  #   v.gui = true
  # end
end
