
var producteurs = [
   [1, 'Bohn', 'Rene', 'Alsace'],
   [2, 'Boxler', 'Albert', 'Alsace'],
   [3, 'Six', 'Paul', 'Alsace'],
   [4, 'Stentz', 'Fernand', 'Alsace'],
   [5, 'Joudeat', 'Lucien', 'Bourgogne'],
   [6, 'Marmagne', 'Bernard', 'Bourgogne'],
   [7, 'Lasnier', 'Pierre', 'Bourgogne'],
   [8, 'Lioger d Harduy', 'Gabriel', 'Bourgogne'],
   [9, 'Moniot', 'Gilbert', 'Bourgogne'],
   [10, 'Fournier', 'Jean Claude', 'Bourgogne'],
   [11, 'Clerget', 'Anne', 'Bourgogne'],
   [12, 'Tortochot', 'Gabriel', 'Bourgogne'],
   [13, 'Grivot', 'Jean', 'Bourgogne'],
   [14, 'Jayer', 'Henri', 'Bourgogne'],
   [15, 'Drouhin', 'Joseph', 'Bourgogne'],
   [16, 'Barbin', 'Bernard', 'Bourgogne'],
   [17, 'Faiveley', 'Guy', 'Bourgogne'],
   [18, 'Tramier', 'Jean', 'Bourgogne'],
   [19, 'Dupaquier', 'Roger', 'Bourgogne'],
   [20, 'Lamy', 'Jean', 'Bourgogne'],
   [21, 'Cornu', 'Edmond', 'Bourgogne'],
   [22, 'Dubreuil Fontaine', 'Pierre', 'Bourgogne'],
   [23, 'Laleure', '', 'Bourgogne'],
   [24, 'Guillemot', 'Pierre', 'Bourgogne'],
   [25, 'Valentin Bouchotte', 'Roger', 'Bourgogne'],
   [26, 'Violot', 'Gilbert', 'Bourgogne'],
   [27, 'Glantenay', 'Louis', 'Bourgogne'],
   [28, 'Monnier', 'Rene', 'Bourgogne'],
   [29, 'De Suremain', 'Robert', 'Bourgogne'],
   [30, 'Desbois', 'Maurice', 'Bourgogne'],
   [31, 'Prudhon', 'Henri', 'Bourgogne'],
   [32, 'Mestre', 'Philippe', 'Bourgogne'],
   [33, 'Prieur', 'Guy', 'Bourgogne'],
   [34, 'Monnier', 'Rene', 'Bourgogne'],
   [35, 'Roulot', 'Guy', 'Bourgogne'],
   [36, 'Sauzet', 'Etienne', 'Bourgogne'],
   [37, 'Delagrange Bachelet', '', 'Bourgogne'],
   [38, 'De Launay', 'Paul', 'Bourgogne'],
   [39, 'De Suremin', 'Hugues', 'Bourgogne'],
   [40, 'Genelot', 'Maurice', 'Bourgogne'],
   [41, 'Juillot', 'Michel', 'Bourgogne'],
   [42, 'Juillot', 'Maurice', 'Bourgogne'],
   [43, 'Menand', 'Jean Claude', 'Bourgogne'],
   [44, 'Feyveley', '', 'Bourgogne'],
   [45, 'Jeannin', 'Andre', 'Bourgogne'],
   [46, 'Monassier', 'Armand', 'Bourgogne'],
   [47, 'Thenard', '', 'Bourgogne'],
   [48, 'Flamand', '', 'Bourgogne'],
   [49, 'Guillot', 'Pierre', 'Bourgogne'],
   [50, 'Chagny', 'Georges', 'Bourgogne'],
   [51, 'Simonet', 'Leon', 'Bourgogne'],
   [52, 'Lapierre', 'Jean', 'Bourgogne'],
   [53, 'Cooperative', '', 'Bourgogne'],
   [54, 'Cooperative', '', 'Bourgogne'],
   [55, 'Michon', 'Philippe', 'Bourgogne'],
   [56, 'Coutelle', 'Jean', 'Beaujolais'],
   [57, 'Desmules', 'Pierre', 'Beaujolais'],
   [58, 'Joubert', 'Claude', 'Beaujolais'],
   [59, 'La Thuilliere', 'Jean', 'Beaujolais'],
   [60, 'Vernus', 'Georges', 'Beaujolais'],
   [61, 'Champier', 'Charles', 'Beaujolais'],
   [62, 'Champagnon', 'Louis', 'Beaujolais'],
   [63, 'Cooperative', '', 'Beaujolais'],
   [64, 'Marius Bel Air', 'Morin', 'Beaujolais'],
   [65, 'Appert', 'Michel', 'Beaujolais'],
   [66, 'Cooperative', '', 'Beaujolais'],
   [67, 'Descombes', 'Jean Ernest', 'Beaujolais'],
   [68, 'Savoye', 'Louis', 'Beaujolais'],
   [69, 'Janin', 'Marcel', 'Beaujolais'],
   [70, 'Trichard', 'Benoit', 'Beaujolais'],
   [71, 'Chalandard', 'Daniel', 'Jura'],
   [72, 'Reverchon', 'Joseph', 'Jura'],
   [73, 'Bourguignon', 'Emile', 'Jura'],
   [74, 'Grand', 'Rene', 'Jura'],
   [75, 'Loye', 'Camille', 'Jura'],
   [76, 'Maire', 'Henri', 'Jura'],
   [77, 'Tissot', 'Andre', 'Jura'],
   [78, 'Michlel', 'Pierre Emile', 'Jura'],
   [79, 'Petit', 'Gerard', 'Jura'],
   [80, 'Devaux', 'Jean Paul', 'Jura'],
   [81, 'Peltier', 'Pierre', 'Jura'],
   [82, 'Mollex', 'Georges', 'Savoie'],
   [83, 'Goy', '', 'Jura'],
   [84, 'Metral', 'Jean', 'Jura'],
   [85, 'Champet', 'Emile', 'Rhone'],
   [86, 'Dumazet', 'Marc', 'Rhone'],
   [87, 'Neyret Gachet', '', 'Rhone'],
   [88, 'Begot', 'Albert', 'Rhone'],
   [89, 'Michelas', 'Robert', 'Rhone'],
   [90, 'Roure', 'Raymond', 'Rhone'],
   [91, 'Chave', 'Gerard', 'Rhone'],
   [92, 'De Boissieu', '', 'Rhone'],
   [93, 'Marsanne', 'Jean', 'Rhone'],
   [94, 'Grippat', 'Jean Louis', 'Rhone'],
   [95, 'Verset', 'Louis', 'Rhone'],
   [96, 'Boisson', 'Jean Pierre', 'Rhone'],
   [97, 'Quiot', 'Pierre', 'Rhone'],
   [98, 'Berard', '', 'Rhone'],
   [99, 'Cooperative', '', 'Rhone'],
   [100, 'Bernard', 'Georges', 'Rhone'],
   [101, 'Verdan', 'Antoine', 'Rhone'],
   [102, 'Cooperative', '', 'Rhone'],
   [103, 'Coulouvrat', 'Michel', 'Rhone'],
   [104, 'Rabasse Chavarin', 'Abel', 'Rhone'],
   [105, 'Roux', 'Charles', 'Rhone'],
   [106, 'Alary', '', 'Rhone'],
   [107, 'Meunier', 'Laurent', 'Rhone'],
   [108, 'Archimbaud', 'Jean', 'Rhone'],
   [109, 'Rey', 'Marcel', 'Rhone'],
   [110, 'Cooperative', '', 'Rhone'],
   [111, 'Zafiropulo', 'Costa', 'Provence'],
   [112, 'Prebost', 'Gaston', 'Provence'],
   [113, 'Gomez', 'Rene', 'Provence'],
   [114, 'Brunet', 'Georges', 'Provence'],
   [115, 'Bordonado', 'Raymond', 'Provence'],
   [116, 'Imbert', 'Christian', 'Corse'],
   [117, 'Cooperative', '', 'Languedoc'],
   [118, 'Cooperative', '', 'Languedoc'],
   [119, 'Cooperative', '', 'Pyrenees'],
   [120, 'Campigna Janvier', '', 'Pyrenees'],
   [121, 'Cooperative', '', 'Pyrenees'],
   [122, 'Dupuy', 'Charles', 'Pyrenees'],
   [123, 'Laurent', 'Pierre', 'Pyrenees'],
   [124, 'Daurat Fort', 'Robert', 'Pyrenees'],
   [125, 'Baldes', 'Jean', 'Sud Ouest'],
   [126, 'Jouffreau', 'Jean', 'Sud Ouest'],
   [127, 'Brumont', 'Alban', 'Sud Ouest'],
   [129, 'Barrere', 'Alfred', 'Sud Ouest']
] ;
  document.getElementById('doublesize').innerHTML = 'Nb producteurs ' +  producteurs.length; 
  document.getElementById('singlesize').innerHTML = 'Nb Elements ' +  producteurs[0].length; 
 