# -*- coding: utf-8; mode: ruby -*-
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

  # Box de base Debian : Debian Jessie amd64 minimal w/ guest additions
  config.vm.box = "debian80"

  # Setup the containers when the VM is first
  # created
  config.vm.provision "shell", path:"./setup-debian/provisioning.sh"

  # Uncomment the following to access the GUI
  # config.vm.provider "virtualbox" do |v|
  #   v.gui = true
  # end
end
