# -*- coding: utf-8; mode: ruby -*-
#VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

  # Box de base Debian : Debian Jessie amd64 minimal w/ guest additions
#  config.vm.box = "oberger/moocbdvm"

  # TODO : execute the script somewhere else than where it will update itself
  # Provision stuff, including what is needed in /vagrant
  config.vm.provision "shell", inline: "docker restart tsp-moocdb-postgres; docker restart tsp-moocdb-web", privileged: false

  # config.vm.network "private_network", ip: "192.168.50.40"

  # Forward port to access the guest machine
  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true

  # Comment-out the following section to hide the GUI
  # config.vm.provider "virtualbox" do |v|
  #   v.gui = true
  # end
end
