#+TITLE: Prise en main rapide de la Box Vagrant du MOOC BD Télécom SudParis
#+OPTIONS: html-link-use-abs-url:nil html-postamble:nil
#+OPTIONS: html-preamble:t html-scripts:t html-style:t
#+OPTIONS: html5-fancy:nil tex:t
#+OPTIONS: toc:nil
#+CREATOR:
#+AUTHOR: Équipe du MOOC Bases de données relationnelles de Télécom-SudParis
#+HTML_CONTAINER: div
#+HTML_DOCTYPE: xhtml-strict
#+HTML_HEAD:
#+HTML_HEAD_EXTRA:
#+HTML_LINK_HOME:
#+HTML_LINK_UP:
#+HTML_MATHJAX:
#+INFOJS_OPT:
#+LATEX_HEADER:
#+LANGUAGE: fr

* Prérequis

- Disposer d'une machine moderne avec un système d'exploitation (64
  bits[fn:5]) sur lequel VirtualBox\trade fonctionne[fn:2]

- Avoir un environnement internet à haut débit pour le téléchargement de l'environnement[fn:4]

- Avoir au moins 2 Go de libre sur un disque dur local

- Maîtriser un minimum l'utilisation d'un système d'exploitation,
  notamment en mode invite de commande (commandes de base DOS ou shell
  Unix, type =cd=, =ls/dir=, etc.).

** Avertissement

/Nous avons fait de notre mieux pour fournir un environnement fonctionnel, basé sur des logiciels libres, mais vous l'utilisez *à vos risques et périls, sans aucune garantie*. Nous ne pouvons être tenus responsables des dommages qui résulteraient de l'utilisation de cet environnement./ 

* Installation

** TODO Installer VirtualBox puis Vagrant

Téléchargez les deux applications depuis leurs sites, ou installez les
paquetages pour votre distribution (si vous êtes sur Linux).

- VirtualBox : https://www.virtualbox.org/wiki/Downloads
- Vagrant : http://www.vagrantup.com/downloads.html


** Initialisation et mise en route

Choisir un dossier de travail dans lequel Vagrant va installer une
*machine virtuelle*, et où les fichiers des TPs vont résider. Ce dossier
doit être choisi sur une partition disposant d'au moins 2 Go d'espace de
stockage libre.

Ouvrir une invite de commande[fn:1] dans ce dossier et entrer :
#+BEGIN_example
vagrant init oberger/moccbdvm
vagrant up
#+END_example

Cela va télécharger la /box/ Vagrant depuis Internet (env. 500 Mo), et
lancer une machine virtuelle VirtualBox[fn:3] en tâche de fond, qui
fournira l'environnement Web que vous allez utiliser.

Pour une explication des commandes de base de Vagrant,
consultez
[[http://docs.vagrantup.com/v2/getting-started/index.html][le guide de démarrage vagrant (en anglais)]].

* Utilisation

** Exerciseur pour les requêtes SQL (semaine 3)

Une fois l'installation terminée, vous pouvez dès à présent tester des
requêtes SQL sur les bases de données fournies pour le MOOC.

Vous n'avez qu'à vous connecter sur l'application Web fournie par la machine virtuelle : http://localhost:8080/bdsqlwiz/appli/

** Travaux pratiques (à partir de la semaine 6)

Dans le cadre du MOOC, vous serez amenés à réaliser des pages PHP pour
dialoguer avec la base de données.

Vous devez placer vos pages dans le sous-répertoire =TP/= qui aura été
créé dans le répertoire de travail où vous avez executé les commandes
d'installation.

Les pages PHP seront alors accessibles depuis http://localhost:8080/TP/

* Maintenance

Les enseignants du MOOC pourront éventuellement publier des
mises-à-jour de l'environnement modèle qui sert de référence à la
machine virtuelle.

Afin de mettre à jour l'environnement déjà installé dans une machine
virtuelle, pour prendre en compte les évolutions de l'environnement
modèle des enseignants, entrez la commande suivante dans une invite de
commande:

#+BEGIN_example
vagrant ssh -c "sudo update-script"
#+END_example

*TODO* Attention: ceci nécessite d'avoir installé un client SSH (cf. [[...FAQ]])

* En savoir plus et résolutions des problèmes

Une version plus complète de cette documentation est disponible sur http://localhost:8080/.

En cas de problème, référez-vous aux forums du MOOC, sur
http://mooc.telecom-sudparis.eu/

* Footnotes

[fn:1] autrement appelé /terminal/, /shell/, selon les systèmes d'exploitation

[fn:2] Nous avons réalisé nos tests sur des ordinateurs portables
professionnels en systèmes GNU/Linux ou Microsoft Windows 7
professional.

[fn:3] la machine virtuelle fait fonctionner un système GNU/Linux /Debian/ minimal avec /Apache/, /PHP/ et /PostgreSQL/

[fn:4] Une fois l'installation de la box réalisée, l'utilisation de la machine virtuelle se fait en local, sans avoir besoin d'une connexion internet.

[fn:5] Si votre système est en 32 bits, référez-vous à la [[./manuel.html#FAQ][FAQ]].


