#+TITLE: Prise en main rapide de la Box Vagrant du MOOC BD
#+OPTIONS: html-link-use-abs-url:nil html-postamble:nil
#+OPTIONS: html-preamble:t html-scripts:t html-style:t
#+OPTIONS: html5-fancy:nil tex:t
#+OPTIONS: toc:nil
#+CREATOR:
#+AUTHOR:
#+HTML_CONTAINER: div
#+HTML_DOCTYPE: xhtml-strict
#+HTML_HEAD:
#+HTML_HEAD_EXTRA:
#+HTML_LINK_HOME:
#+HTML_LINK_UP:
#+HTML_MATHJAX:
#+INFOJS_OPT:
#+LATEX_HEADER:

* Prérequis

- Disposer d'une machine avec un système d'exploitation moderne 64
  bits sur lequel VirtualBox\trade fonctionne

- Avoir au moins 2 Go de libre sur un disque dur local

- Maîtriser un minimum l'utilisation d'un système d'exploitation,
  notamment en mode invite de commande (commandes de base DOS ou shell
  Unix, type =cd=, =ls/dir=, etc.).

* Installation

** TODO Installer Vagrant et VirtualBox

- Vagrant : http://www.vagrantup.com/downloads.html
- VirtualBox : https://www.virtualbox.org/wiki/Downloads

** Initialisation et mise en route

Choisir un dossier de travail dans lequel vagrant va installer une
machine virtuelle, et où les fichiers des TPs vont résider. Ce dossier
doit être choisi sur une partition disposant d'au moins 2 Go d'espace de
stockage libre.

Ouvrir une invite de commande dans ce dossier et entrer :
#+BEGIN_example
vagrant init oberger/moccbdvm
vagrant up
#+END_example

* Utilisation

** Site

Une fois l'installation terminée, vous pouvez dès à présent tester les requêtes de votre choix sur les bases de données fournies par le MOOC.

Vous n'avez qu'à vous connecter sur http://localhost:8080/bdsqlwiz/appli/.

** Travaux pratiques (à partir de la semaine 6)

Dans le cadre du MOOC, vous serez amenés à utiliser des pages php pour dialoguer avec la base de données.

Vous devez placer vos pages dans le répertoire TP qui a été créé dans le même répertoire où vous avez executé les commandes d'installation.

Elles seront alors accessibles depuis http://localhost:8080/TP/.

* Maintenance

Les enseignants du MOOC ont la possibilité de modifier l'environnement
modèle qui sert de référence à la machine virtuelle.

Afin de mettre à jour l'environnement déjà installé dans une machine
virtuelle, pour prendre en compte les évolutions de l'environnement
modèle des enseignants, entrez la commande suivante dans une invite de
commande:

#+BEGIN_example
vagrant ssh -c "sudo update-script"
#+END_example

*TODO* Attention: ceci nécessite d'avoir installé un client SSH (cf. [[...FAQ]])

* En savoir plus et résolutions des problèmes

Une version plus complète de cette documentation est disponible sur http://localhost:8080/.

En cas de problème, référez-vous aux forums du MOOC, sur
http://mooc.telecom-sudparis.eu/

